class MessageState:
    DISCOVERED = "DISCOVERED"
    FETCHED = "FETCHED"
    INSERTING = "INSERTING"
    INSERTED = "INSERTED"
    SUPPRESSED_DUPLICATE = "SUPPRESSED_DUPLICATE"
    FAILED_RETRY = "FAILED_RETRY"
    FAILED_PERM = "FAILED_PERM"
